# Convert aliases into something the mac "say" command can read
aliases = {
    "bangerth": "Wolfgang",
    "jdannberg": "Yuliana",
    "gassmoeller": "Rene",
    "bobmyhill": "Bob",
    "tjhei": "Teemo",
    "MFraters": "Menno",
    "anne-glerum": "Anna",
    "Djneu": "Derek",
    "mfmweerdesteijn": "Mica",
    "poulamiiroy": "Poulami",
    "RanpengLi": "Ranpeng",
    "mgouiza": "Mo",
    "Wang-yijun": "Yijun",
    "srivatsvyas": "Srivatsan",
    "alarshi": "Aarooshi",
    "chameerasilva": "Chameera",
    "zjiaqi2018": "Jiaqi",
    "cedrict": "Cedric",
    "marcel112358": "Marcel",
    "danieldouglas1992": "Katniss Everdeen",
    "ljhwang": "Lorraine",
    "ryanstoner1": "Ryan",
    "lhy11009": "Howian",
}

# Add descriptors to choose at random
descriptors = [
    "awesome",
    "incredible",
    "profound",
    "spectacular",
    "Turing-prize worthy",
    "geologically significant",
    "world-changing",
    "utterly remarkable",
    "truly wonderful",
    "practically perfect in every way",
    "astounding",
    "paradigm-defining",
    "stupendous",
    "all-mighty",
    "enchanting",
]
